#!/bin/bash

# source the ciop functions (e.g. ciop-log, ciop-getparam)
source ${ciop_job_include}

# source job functions
source ${_CIOP_APPLICATION_PATH}/flh-proc/lib/functions.sh

set_env

get_pars || exit $?

# loop and process all MERIS products
while read inputfile 
do
  main ${inputfile} || exit $?
done

exit 0
